### ISSUE TITLE
Unify the payment and zkapp command logic in sequencer

### ISSUE THREAD

**Issue by MartinOndejka** [zeko-labs/zeko#131]
Currently there are 2 functions `apply_signed_command` and `apply_zkapp_command`. The logic can be unified to the one function `apply_user_command`.

**Comment by L-as** [comment]
How?

**Comment by MartinOndejka** [comment]
The transaction logic is unified under `apply_transaction_first_pass` and `apply_transaction_second_pass`. A lot of the logic is duplicated in the `apply_signed_command` and `apply_zkapp_command` and multiple times I've accidentally updated only one of them resulting in a bug. There should be no duplication of the same code.

**Comment by MartinOndejka** [comment]
It's just a simple refactor, nothing fancy.
